### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by nicwortel**
This PR adds support for PHP 8.0. In order to do so, I had to drop support for PHP versions <7.1, mostly because PHPUnit 9 (the first version to support PHP 8) only supports PHP 7.1 and higher, so older PHP versions can no longer be tested against.

### CODE REVIEW

**Comment by ramsey** [comment]
According to the failures, it looks like mockery/mockery 1.4 requires at least PHP 7.3.

**Comment by ramsey** [comment]
And other failures are related to Python versions. I'll need to look at the build system to see if something should be updated.

**Comment by nicwortel** [comment]
> According to the failures, it looks like mockery/mockery 1.4 requires at least PHP 7.3.

Good catch. It seems like mockery/mockery ^1.3 should work as well. I've just committed a lower minimum version constraint. I hope you are not loosing a lot of build credits with all these jobs...

> And other failures are related to Python versions. I'll need to look at the build system to see if something should be updated.

It seems like Python 2.6 was supported by Travis CI on Ubuntu Trustu (14.04) [but not on Xenial](https://travis-ci.community/t/issue-with-python-2-6-on-linux/3861/3) (16.04), [which is the default distro for Travis builds since April 2019](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment).

According to https://docs.travis-ci.com/user/languages/python/#python-versions 3.3 is also not available on Xenial.

What would you like me to do? I could simply drop Python 2.6 and 3.3 from the build matrix, or I could try to make them run on Trusty...

**Comment by nicwortel** [comment]
> > According to the failures, it looks like mockery/mockery 1.4 requires at least PHP 7.3.
> 
> Good catch. It seems like mockery/mockery ^1.3 should work as well. I've just committed a lower minimum version constraint. I hope you are not loosing a lot of build credits with all these jobs...

In fact, I now realize that PHPUnit 9 also requires PHP ^7.3. I don't think there is an (easy) way around this: in order to support PHP 8.0, support for PHP < 7.3 has to be dropped. Would that be acceptable?

**Comment by ramsey** [comment]
That should be fine.

>  I hope you are not loosing a lot of build credits with all these jobs.

Does Travis CI require build credits now? If so, I'm not aware. 😁

**Comment by nicwortel** [comment]
> Does Travis CI require build credits now? If so, I'm not aware. :grin: 

[Yes, at least at travis-ci.com](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). I'm not sure about travis-ci.org, so maybe this project is not affected.

**Comment by ramsey** [comment]
Took care of a few changes to the build process and got it passing on GitHub Actions. I've merged in your changes. Thanks a bunch!

**Comment by nicwortel** [comment]
Thanks a lot! I'm looking forward to a new version release so I can continue using pygments on PHP 8 :smiley:

**Comment by ramsey** [comment]
@nicwortel Would it cause problems for you if I released these changes as version 2?

**Comment by nicwortel** [comment]
@ramsey no, I think that should work just fine :+1:

**Comment by nicwortel** [comment]
@ramsey is there anything that has to be done before version 2 can be released? Anything I can help with?

**Comment by ramsey** [comment]
Apologies for the delay, @nicwortel! Version 2.0.0 is out now, with PHP 8 support. Thanks!

**Pull request merged**
